apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets-repo.yaml
  - external-secrets.yaml

configMapGenerator:
  - name: external-secrets-values
    namespace: external-secrets
    files:
      - values-external-secrets.yaml

generatorOptions:
  disableNameSuffixHash: true
