apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - docker-registry-repo.yaml
  - docker-registry.yaml

configMapGenerator:
  - name: docker-registry-values
    namespace: openchoreo-build-plane
    files:
      - values-docker-registry.yaml

generatorOptions:
  disableNameSuffixHash: true