apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-repo.yaml
  - cert-manager.yaml

configMapGenerator:
  - name: cert-manager-values
    namespace: cert-manager
    files:
      - values-cert-manager.yaml

generatorOptions:
  disableNameSuffixHash: true
