apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openchoreo-helm-repo.yaml
  - openchoreo-cert-manager.yaml
  - openchoreo-certs.yaml
  - openchoreo-gateway-api.yaml
  - openchoreo-control-plane.yaml
  - openchoreo-build-plane.yaml
  - openchoreo-data-plane.yaml
  - openchoreo-docker-registry.yaml
  - openchoreo-external-secrets.yaml

configMapGenerator:
  - name: openchoreo-control-plane-values
    namespace: openchoreo-control-plane
    files:
      - values-cp.yaml
  - name: openchoreo-build-plane-values
    namespace: openchoreo-build-plane
    files:
      - values-bp.yaml
  - name: dataplane-values
    namespace: openchoreo-data-plane
    files:
      - values-dp.yaml

generatorOptions:
  disableNameSuffixHash: true