apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repo.yaml
  - openchoreo-control-plane.yaml
  - non-prod-dataplane.yaml
  - prod-dataplane.yaml
  - openchoreo-build-plane.yaml

configMapGenerator:
  - name: openchoreo-control-plane-values
    namespace: openchoreo-control-plane
    files:
      - values-cp.yaml
  - name: non-prod-dataplane-values
    namespace: non-prod-dataplane
    files:
      - values-non-prod-dp.yaml
  - name: prod-dataplane-values
    namespace: prod-dataplane
    files:
      - values-prod-dp.yaml
  - name: openchoreo-build-plane-values
    namespace: openchoreo-build-plane
    files:
      - values-bp.yaml

generatorOptions:
  disableNameSuffixHash: true