cert-manager:
  enabled: false

gateway:
  enabled: true
  httpPort: 7080
  httpsPort: 7443
  envoy:
    enabled: true
    mountTmpVolume: true

clusterAgent:
  enabled: true
  serverUrl: wss://cluster-gateway.openchoreo-control-plane.svc.cluster.local:8443/ws
  planeName: non-prod
  planeType: dataplane

external-secrets:
  scopedRBAC: true
  scopedNamespace: non-prod-dataplane

fakeSecretStore:
  enabled: false
