argo-workflows:
  server:
    enabled: false
    serviceType: LoadBalancer
    servicePort: 2746
    authModes:
      - server

registry:
  service:
    type: LoadBalancer
    port: 5000

global:
  defaultResources:
    registry:
      endpoint: "host.k3d.internal:10082"

external-secrets:
  enabled: false

fluentBit:
  enabled: false